version: "3.9"
services:
  polytech-smart-house-postgres:
    image: postgres:16
    container_name: polytech-smart-house-postgres
    environment:
      POSTGRES_DB: "polytech-smart-house"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - polytech-smart-house-network

networks:
  polytech-smart-house-network: