services:
  polytech-smart-house-postgres:
    image: postgres:16-bookworm
    container_name: polytech-smart-house-postgres
    environment:
      POSTGRES_DB: "polytech-smart-house"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - polytech-smart-house-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d polytech-smart-house" ]
      interval: 10s
      timeout: 5s
      retries: 5

  polytech-smart-house-mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: polytech-smart-house-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - polytech-smart-house-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1883" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  polytech-smart-house-network: