spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:polytech-smart-greenhouse-postgres}:${DB_PORT:5432}/${DB_NAME:polytech-smart-house}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

mqtt:
  broker:
    url: tcp://${MQTT_HOST:polytech-smart-greenhouse-mosquitto}:${MQTT_PORT:1883}
  client:
    id: greenhouse-server

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}